---
- hosts: utility
  sudo: yes
  roles:
  - base
  - monit
  - exim4
  - apt_mirror
  - account_site
  - monit_site
  - nut_site
  - pasta_site
  - inspircd
  - iperf
  - papercut
  - preseed_site
  - tftp
  - jekyll
