---
- name: Install Python Requests
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items:
    - py-requests
    - py-jinja2

- name: Install the MAC updater
  copy:
    src: openbsd-dhcpd-supervisor.py
    dest: /usr/local/sbin/openbsd-dhcpd-supervisor
    owner: root
    group: wheel
    mode: 0755

- name: Install MAC Update cronjob
  copy:
    src: dhcpd-updater.crontab
    dest: /etc/crontab.d/
    owner: root
    group: wheel
    mode: 0644
  notify:
    - crontab

- name: Install pf Rules
  copy:
    src: 10-mac-updater
    dest: /etc/pf.d/10-mac-updater
    owner: root
    group: wheel
    mode: 0644
  notify:
    - pf.conf
