---
slapd_groups:
- name: Pantheon
  gidNumber: 31337
  members:
  - ahalbert
  - ahmedusthefirst
  - Bardiya
  - cliffhanger
  - ErikLee
  - kjh061000
  - MatchesMalone
  - phy1729
  - revertTS
  - thechairman
  - vanquish

- name: Paper Creditors
  gidNumber: 1455
  members:
  - sheila.kelly
  - vbrunell
  - Wendik
  - Fladagus

- name: Realm Admins
  gidNumber: 1337
  members:
  - harpham
  - maldridge
  - phy1729
  - dinoocch
  - m_wynn

- name: Local Admins
  gidNumber: 9271
  members:
  - Siosilvar
  - Fhqwhgads

- name: Print Admins
  gidNumber: 1934
  members:
  - Fhqwhgads
